/* ============================================================
   ANIMATION INVENTORY — the canonical catalogue of every distinct animation
   system in the site. A guard against regressions: future work should EXTEND
   this, never collapse the variety back into a single fade-up.

   Each entry: { id, type, name, usedOn }
     type: 'background' | 'component' | 'text' | 'nav' | 'foreground'
         | 'cursor' | 'transition' | 'overlay' | 'audio' | 'cinematic'
         | 'performance'

   Not imported by the app — it is a catalogue. The FOREGROUND section lists the
   page-specific compositions; `qa/foreground-inventory.mjs` is the other half:
   it loads every route and counts the `data-fx` markers that are on screen, and
   FOREGROUND-DETAILS.md (generated from it) lists every separate behaviour
   inside those compositions.
   ============================================================ */

/* ---- 67 distinct canvas background scenes ---- */
const BACKGROUND_SCENES = [
  ['home-core', 'Home Core composite (arcs + particles + grid)'],
  ['audio-signal-wall', 'Audio Signal Wall (full-width spectrum)'],
  ['radial-audio-core', 'Radial Audio Core (spectrum ring)'],
  ['signal-spectrum-field', 'Signal Spectrum Field (stacked spectrum)'],
  ['orbital-command', 'Orbital Command ring'],
  ['hex-tunnel', 'Perspective Hex Tunnel'],
  ['polar-status', 'Polar Status dial'],
  ['topology-pulse', 'Topology Pulse contours'],
  ['commerce-pipeline', 'Commerce Order Pipeline'],
  ['workflow-river', 'Workflow River streamlines'],
  ['permission-orbit', 'Permission Orbit (role nodes)'],
  ['data-interface-wave', 'Data Interface oscilloscope'],
  ['client-portal-gate', 'Client Portal iris gate'],
  ['research-blackout', 'Research Blackout (redaction)'],
  ['motion-curve-field', 'Motion Curve Field (easings)'],
  ['interface-lab-shape', 'Interface Lab specimens'],
  ['architecture-layer', 'Architecture Layer stack'],
  ['tooling-console', 'Tooling Console terminal'],
  ['musebase-coordination', 'Musebase Coordination orbit'],
  ['unknown-silhouette', 'Unknown System silhouette'],
  ['contact-transmission', 'Contact Transmission rings'],
  ['status-pulse-grid', 'Status Pulse Grid'],
  ['privacy-quiet-grid', 'Privacy Quiet Grid'],
  ['error-signal-lost', 'Error Signal Lost (404)'],
  ['magnetic-vector', 'Magnetic Vector field'],
  ['radar-cutaway', 'Radar Cutaway sweep'],
  ['isometric-infra', 'Isometric Infrastructure'],
  ['redacted-timeline-branch', 'Redacted Timeline Branch'],
  ['liquid-glass-operational', 'Liquid Glass capsules'],
  ['node-compression', 'Node Compression cluster'],
  ['split-prism', 'Split Prism panes'],
  ['glyph-compiler', 'Glyph Compiler'],
  ['compass-vector', 'Compass Vector field'],
  ['heatmap-control', 'Operational Heatmap'],
  ['dependency-graph', 'Dependency Graph DAG'],
  ['build-pipeline', 'Build Pipeline stages'],
  ['scheduling-grid', 'Scheduling Grid'],
  ['transaction-wave', 'Transaction Wave ticker'],
  ['trigger-action-pulse', 'Trigger→Action pulses'],
  ['dashboard-tiles', 'Dashboard Tiles bento'],
  ['data-stream-ribbons', 'Data Stream Ribbons'],
  ['secure-boundary', 'Secure Boundary perimeter'],
  // retained base scenes (still distinct, still in use)
  ['architectural-grid', 'Architectural Grid'],
  ['blackout-silhouette', 'Blackout Silhouette'],
  ['circuit-trace', 'Circuit Trace'],
  ['command-terminal', 'Command Terminal'],
  ['concentric-gate', 'Concentric Gate'],
  ['data-rain', 'Data Rain'],
  ['flow-field', 'Flow Field'],
  ['glass-prism', 'Glass Prism'],
  ['glyph-field', 'Glyph Field'],
  ['heatmap-grid', 'Heatmap Grid'],
  ['hex-lattice', 'Hex Lattice'],
  ['isometric-module', 'Isometric Module'],
  ['liquid-metal', 'Liquid Metal'],
  ['magnetic-particles', 'Magnetic Particles'],
  ['network-constellation', 'Network Constellation'],
  ['orbital-node', 'Orbital Node'],
  ['polar-radar', 'Polar Radar'],
  ['redaction-matrix', 'Redaction Matrix'],
  ['signal-wave', 'Signal Wave oscilloscope'],
  ['spline-ribbon', 'Spline Ribbon'],
  ['timeline-pulse', 'Timeline Pulse'],
  ['topographic-lines', 'Topographic Lines'],
  ['vector-compass', 'Vector Compass'],
  ['voronoi-cell', 'Voronoi Cell'],
  ['wave-interference', 'Wave Interference'],
];

/* ---- component / text / nav / form / cursor / transition / overlay ---- */
const OTHER = [
  // text reveals
  ['text-kinetic-char', 'text', 'Kinetic char slit reveal', ['hero titles']],
  ['text-kinetic-word', 'text', 'Kinetic word-mask reveal', ['hero titles']],
  ['text-reveal-fadeup', 'text', 'RevealText fade-up', ['body']],
  ['text-reveal-maskup', 'text', 'RevealText clip mask-up', ['manifesto lines']],
  ['text-reveal-scanx', 'text', 'RevealText horizontal scan wipe', ['labels']],
  ['text-reveal-splity', 'text', 'RevealText split-axis', ['headings']],
  ['text-reveal-pop', 'text', 'RevealText radial pop', ['tags']],
  ['text-reveal-slidein', 'text', 'RevealText slide-in', ['split body']],
  ['text-sectionheader', 'text', 'SectionHeader staged blur reveal', ['all sections']],

  // ---- component reveal profiles (revealProfiles.js): one distinct entrance
  //      language PER BLOCK, applied via <Reveal> / <RevealGroup>. The fix for
  //      "every box fades up the same way." ----
  ['reveal-slide-left', 'component', 'Slide in from inline-start', ['split body', 'hero intro']],
  ['reveal-slide-right', 'component', 'Slide in from inline-end', ['contact email row']],
  ['reveal-skew-in', 'component', 'Skewed slide settle', ['accent rows']],
  ['reveal-settle-down', 'component', 'Drop in from above', ['footer lead']],
  ['reveal-scan-x', 'component', 'Horizontal scan-mask wipe', ['eyebrows', 'manifesto eyebrow']],
  ['reveal-scan-x-reverse', 'component', 'Reverse scan-mask wipe', ['labels']],
  ['reveal-mask-up', 'component', 'Clip mask-up reveal', ['manifesto lines']],
  ['reveal-mask-down', 'component', 'Clip mask-down reveal', ['panels']],
  ['reveal-curtain-split', 'component', 'Center curtain split reveal', ['manifesto lines']],
  ['reveal-depth-rise', 'component', 'Scale-from-behind depth rise', ['hero actions', 'closer header']],
  ['reveal-zoom-through', 'component', 'Zoom-through from large scale', ['quote block']],
  ['reveal-split-y', 'component', 'Vertical split open', ['stats header']],
  ['reveal-unfold-x', 'component', 'Horizontal unfold from edge', ['bars']],
  ['reveal-radial-pop', 'component', 'Radial spring pop', ['tags']],
  ['reveal-chip-pop', 'component', 'Chip spring pop', ['chips']],
  ['reveal-module-snap', 'component', 'Spring snap into grid', ['modules']],
  ['reveal-orbital-card', 'component', 'Rotate-into-place like an orbit node', ['cards']],
  ['reveal-rise-rotate', 'component', 'Rise with slight rotation', ['footer columns']],
  ['reveal-flip-in', 'component', '3D rotateY flip-in', ['inquiry cards']],
  ['reveal-terminal-open', 'component', 'Terminal-window scaleY open', ['studio panels']],
  ['reveal-glass-materialize', 'component', 'De-blur zoom-out glass materialize', ['callout block']],
  ['reveal-data-materialize', 'component', 'Blur + scale data materialize', ['card grids']],
  ['reveal-reality-assemble', 'component', 'Disintegrate→assemble into reality', ['feature/Musebase block']],
  ['reveal-blur-focus', 'component', 'Chromatic blur-to-focus lock', ['headings']],
  ['reveal-diagonal-slice', 'component', 'Diagonal clip-path slice-in', ['split aside panel']],
  ['reveal-redacted-unlock', 'component', 'Redaction bar slides away to unlock', ['redacted cards', 'module rows']],
  ['reveal-node-sequence', 'component', 'Sequential node slide', ['feature modules list']],
  ['reveal-step-activate', 'component', 'Process-step activation slide', ['process steps']],
  ['reveal-count-rise', 'component', 'Stat block count rise', ['stats', 'hero metrics']],
  ['reveal-bracket-in', 'component', 'Bracketed blur-scale settle', ['panels']],
  ['reveal-depth-stack-rise', 'component', 'Stacked-layer depth rise', ['stacked cards']],
  ['reveal-hex-cell-form', 'component', 'Hex-cell spring form', ['module groups']],

  // ---- per-block SectionHeader entrance variants (no two blocks share one) ----
  ['header-variant-up', 'text', 'SectionHeader rise (default)', ['hero/manifesto']],
  ['header-variant-left', 'text', 'SectionHeader slide-left', ['split', 'redacted']],
  ['header-variant-right', 'text', 'SectionHeader slide-right', ['modules']],
  ['header-variant-depth', 'text', 'SectionHeader depth scale-in', ['cards', 'storyboard', 'work portals']],
  ['header-variant-split', 'text', 'SectionHeader vertical split', ['stats']],
  ['header-variant-scan', 'text', 'SectionHeader scan-mask wipe', ['process', 'contact']],

  // ---- reveal primitives ----
  ['reveal-primitive-single', 'component', '<Reveal> single-element profile host', ['site-wide']],
  ['reveal-primitive-group', 'component', '<RevealGroup> staggered profile host', ['grids/lists']],

  // components
  ['card-bracket-draw', 'component', 'DataPanel corner-bracket draw on view', ['split panels']],
  ['card-reveal-scan', 'component', 'DataPanel one-shot reveal scan', ['split panels']],
  ['pill-dot-pulse', 'component', 'Pill live status dot pulse', ['status pills']],
  ['eyebrow-ping', 'component', 'Section eyebrow signal ping', ['all sections']],
  ['footer-telemetry', 'component', 'Footer telemetry signal rail', ['footer']],
  ['footer-wordmark', 'component', 'Footer dissolving wordmark', ['footer']],
  ['glitch-line', 'component', 'Glitch divider line', ['stats/404']],
  ['timeline-node', 'component', 'Timeline node activation + branch', ['timeline']],
  ['datapanel-arm', 'component', 'DataPanel in-view arm sequence', ['panels']],
  // buttons
  ['btn-magnetic', 'component', 'Magnetic button pull', ['CTAs']],
  ['btn-sweep', 'component', 'Button hover light-sweep', ['CTAs']],
  ['btn-press', 'component', 'Button press compression', ['CTAs']],
  ['btn-icon-shift', 'component', 'Button icon path shift', ['CTAs']],
  // nav
  ['nav-hover-intent', 'nav', 'Hover-intent open/close gating', ['header']],
  ['nav-radial-deploy', 'nav', 'Radial menu deploy from item', ['header']],
  ['nav-ring-stroke', 'nav', 'Menu ring stroke-draw', ['header']],
  ['nav-connector-draw', 'nav', 'Menu connector stroke-draw', ['header']],
  ['nav-node-pop', 'nav', 'Menu orbit-node spring pop', ['header']],
  ['nav-selector-swing', 'nav', 'Menu selector arc swing', ['header']],
  ['nav-label-clip', 'nav', 'Menu route label clip reveal', ['header']],
  ['nav-active-pulse', 'nav', 'Active route live pulse', ['header']],
  ['mobile-command-rail', 'nav', 'Mobile command-surface rail', ['mobile menu']],
  ['mobile-group-expand', 'nav', 'Mobile group accordion expand', ['mobile menu']],
  // cursor
  ['cursor-default', 'cursor', 'Designed cursor — default ring', ['site']],
  ['cursor-link', 'cursor', 'Cursor link state', ['links']],
  ['cursor-nav', 'cursor', 'Cursor nav state', ['nav']],
  ['cursor-audio', 'cursor', 'Cursor audio state', ['audio button']],
  ['cursor-label', 'cursor', 'Cursor names what a press does (View / Drag / custom data-cursor-label)', ['cards', 'rails']],
  ['cursor-drag', 'cursor', 'Cursor grips while dragging a rail, slider or scrubber', ['drag surfaces']],
  // transitions / overlays / audio
  ['route-current', 'transition', 'Route current — a thin red line travels the viewport, destination written at its end', ['all']],
  ['page-handover', 'transition', 'Page hand-over at a dim level (never fully dark, no opaque cover)', ['all']],
  ['route-fallback', 'transition', 'Lazy-route loading sweep', ['all']],
  ['boot-sequence', 'transition', 'Cinematic boot calibration (START begins the music inside the click)', ['entry']],
  ['overlay-scanline', 'overlay', 'Static scanline veil (the sweeping band was removed: ~15 fps)', ['site']],
  ['overlay-noise', 'overlay', 'Global film-grain noise', ['site']],
  ['audio-nav-visualizer', 'audio', 'Nav mini audio visualizer + live / tap-to-play states', ['header']],
  ['palette-overlay', 'overlay', 'Command search — centred portal overlay with body-text excerpts', ['Ctrl/⌘ K', '/']],
  ['shortcuts-panel', 'overlay', 'Keyboard shortcuts panel', ['?']],
  ['blueprint-mode', 'overlay', 'Blueprint mode — outlines, names and counts every marked foreground detail', ['B']],
  ['footer-directory', 'nav', 'Footer as a directory of the whole site: six columns of named groups, a search field, a section row with live page counts, a strip of what is new, a legal row; on a phone the columns fold into disclosures', ['footer']],
  // 20-second System Synthesis cinematic — full-screen takeover OVERLAY (not a page)
  ['synth-camera-push', 'cinematic', 'Synthesis camera push-in + ignition/collapse punches', ['synthesis-overlay']],
  ['synth-streaks', 'cinematic', 'Synthesis constant radial speed-lines', ['synthesis-overlay']],
  ['synth-black-start', 'cinematic', 'Synthesis P1 — black start core + telemetry', ['synthesis-overlay']],
  ['synth-core-ignition', 'cinematic', 'Synthesis P2 — concentric ring ignition + orbit nodes', ['synthesis-overlay']],
  ['synth-grid-construction', 'cinematic', 'Synthesis P3 — architectural grid construction', ['synthesis-overlay']],
  ['synth-fragment-assembly', 'cinematic', 'Synthesis P4 — fragments pulled inward', ['synthesis-overlay']],
  ['synth-north-activation', 'cinematic', 'Synthesis P5 — Hanoryx North + route orbit', ['synthesis-overlay']],
  ['synth-systems-expansion', 'cinematic', 'Synthesis P6 — system modules with micro-motifs', ['synthesis-overlay']],
  ['synth-timeline-pull', 'cinematic', 'Synthesis P7 — project timeline + redacted silhouettes', ['synthesis-overlay']],
  ['synth-interface-convergence', 'cinematic', 'Synthesis P8 — panels converge + radial menu flash', ['synthesis-overlay']],
  ['synth-signal-wall', 'cinematic', 'Synthesis P9 — full-screen audio/signal wall', ['synthesis-overlay']],
  ['synth-system-lock', 'cinematic', 'Synthesis P10 — compression + wordmark lock-in', ['synthesis-overlay']],
  ['synth-release', 'cinematic', 'Synthesis P11 — release dissolve into the live home', ['synthesis-overlay']],
  ['synth-overlay-seizure', 'cinematic', 'Full-screen overlay clip-in viewport seizure', ['synthesis-overlay']],

  // performance systems
  ['perf-fast-scroll-governor', 'performance', 'Fast-scroll governor (scene/reveal/cursor mode)', ['site-wide']],
  ['perf-scene-fast-freeze', 'performance', 'Scenes freeze last frame during fast scroll', ['backgrounds']],
  ['perf-scene-eager-skip', 'performance', 'Skip painting scenes flown past', ['backgrounds']],
  ['perf-reveal-snap', 'performance', 'Reveals snap in cheaply during fast scroll', ['components']],
  ['perf-scenes-global-pause', 'performance', 'Pause all page scenes during overlays', ['backgrounds']],
  ['perf-viewport-director', 'performance', 'Measured --viewport-h + layout-settled refresh', ['stages']],

  // route current — one direction of travel per section (categoryTransitions.js)
  ['route-current-home', 'transition', 'Route current rises from the bottom', ['/']],
  ['route-current-systems', 'transition', 'Route current crosses left to right', ['/systems']],
  ['route-current-north', 'transition', 'Route current falls top to bottom', ['/north', '/engineering', '/lab']],
  ['route-current-work', 'transition', 'Route current crosses right to left', ['/work']],
  ['route-current-company', 'transition', 'Route current opens outward from the middle', ['/company']],
  ['route-current-contact', 'transition', 'Route current rises from the bottom', ['/contact']],
  ['route-current-legal', 'transition', 'Route current falls top to bottom', ['/legal/*']],
];

/* ============================================================
   FOREGROUND — the part of each page that sits in front of its background.
   `toolkit` pieces live in components/fx and are reused; `aside` pieces are
   hero objects (hero.aside.kind); `signature` pieces are whole-block
   compositions ({ type: 'signature', kind }). Each signature is its own lazy
   chunk (components/signatures/registry.js). The `end-` entries are page endings
   ({ type: 'closer', kind }, components/closers/registry.js): each page closes
   on a composition of its own — a game, a calculator, a checklist, a drawing —
   and none is a call to action (qa/endings.mjs holds that line).
   ============================================================ */
const FOREGROUND = [
  // ---- toolkit (components/fx) ----
  ['fx-tilt-surface', 'foreground', 'TiltSurface — a surface that leans toward the pointer (eased through registered CSS vars)', ['asides', 'cards']],
  ['fx-spotlight-card', 'foreground', 'SpotlightCard — a light that follows the pointer across the card', ['card grids']],
  ['fx-proximity-text', 'foreground', 'ProximityText — letters swell and brighten as the pointer nears', ['404', 'big titles']],
  ['fx-scramble-text', 'foreground', 'ScrambleText — characters decode into the real text on hover or entry', ['codes', 'labels', 'email']],
  ['fx-scroll-words', 'foreground', 'ScrollWords — a paragraph lights word by word as it scrolls', ['manifestos', 'split leads']],
  ['fx-odometer', 'foreground', 'Odometer — digits roll to their value', ['stats', 'counters']],
  ['fx-velocity-marquee', 'foreground', 'VelocityMarquee — a ticker whose speed follows scroll velocity', ['manifestos']],
  ['fx-glide-tabs', 'foreground', 'GlideTabs — a tab list whose ink glides between tabs', ['signatures']],
  ['fx-accordion', 'foreground', 'Accordion — eased-height disclosure with a plus that turns', ['lists']],
  ['fx-compare-slider', 'foreground', 'CompareSlider — drag, key or tap a handle to peel one layer from another', ['surface compare']],
  ['fx-hover-index', 'foreground', 'HoverIndex — big rows; a red rule glides to the hovered row, codes scramble, a preview trails the cursor (touch: every row shows its own detail)', ['index lists']],
  ['fx-drag-rail', 'foreground', 'DragRail — grab and fling a rail (momentum), ← → buttons and keys, a progress thumb', ['card rails']],
  ['fx-scroll-rail', 'foreground', 'ScrollRail — a section rail on long pages: the current tick stretches and lights, hover names it, click glides there', ['long pages']],
  ['fx-glyph', 'foreground', 'Glyph — 27 drawn SVG glyphs that animate on hover', ['cards', 'rows']],
  ['fx-progress-ring', 'foreground', 'ProgressRing — a ring that fills from a value', ['review aids', 'budgets']],
  ['fx-arrow-link', 'foreground', 'ArrowLink — an inline link whose arrow slides on hover', ['links']],
  ['fx-keycap', 'foreground', 'KeyCap — a drawn keyboard key with a pressed, lit state', ['shortcuts', 'keyboard map', 'component bench']],

  // ---- hero asides (hero.aside.kind) ----
  ['aside-orbit-nav', 'foreground', 'Orbit nav — four doors into the site on three orbits', ['home']],
  ['aside-case-deck', 'foreground', 'Case deck — the case studies as a fanning deck of files, each a link', ['work']],
  ['aside-logo-plate', 'foreground', 'Logo plates — the Musebase mark on stacked plates drifting at their own depths', ['work/musebase']],
  ['aside-engine-viewport', 'foreground', 'Engine viewport — a framed miniature viewport leaning toward the pointer', ['work/yk-engine']],
  ['aside-basket', 'foreground', 'Basket tiles — tap abstract tiles and the basket count rolls up', ['work/customer-product']],
  ['aside-dot-field', 'foreground', 'Dot field — ~750 dots under a soft lens that follows the pointer', ['work/internal-crm']],
  ['aside-identity-card', 'foreground', 'Identity card — leans toward the pointer, turns over to the company and its team', ['company']],
  ['aside-split-flap', 'foreground', 'Split-flap board — letters flip to each new word; press a row for the next', ['company/careers']],
  ['aside-tension-dials', 'foreground', 'Tension dials — three sliders; push one to an extreme and its cost is named', ['company/principles']],
  ['aside-system-map', 'foreground', 'System map — seven areas around a shared core; nodes open in place to a card', ['systems']],
  ['aside-north-compass', 'foreground', 'Compass — the needle follows the pointer and settles on one of four pillars', ['north']],
  ['aside-live-budget', 'foreground', 'Live budget — fps, active scenes, loops and quality tier read from this page, this device', ['engineering']],

  // ---- signature blocks ----
  ['sig-work-portals', 'foreground', 'Work portals — hover or focus a project to open it, each with its own art; supporting studies sit quieter', ['home', 'work']],
  ['sig-layer-stack', 'foreground', 'Layer stack — three CSS-3D plates part as you scroll; hover or focus lifts one clear', ['home', 'north/architecture']],
  ['sig-chronology-strip', 'foreground', 'Chronology strip — a line draws as it scrolls in and the undated phase nodes light in turn', ['home', 'company']],
  ['sig-coordination-lab', 'foreground', 'Coordination lab — an illustration of many things kept in step', ['work/musebase']],
  ['sig-engine-editor', 'foreground', 'Engine editor — a small demo of authoring entities in an editor and running them in a player (an illustration, not the engine)', ['work/yk-engine']],
  ['sig-engine-pipeline', 'foreground', 'Engine pipeline — pick a stage (click, tap, ← →) and a token travels there', ['work/yk-engine']],
  ['sig-engine-anatomy', 'foreground', 'Engine anatomy — an interactive blueprint of how the engine is organised', ['work/yk-engine']],
  ['sig-experience-storyboard', 'foreground', 'Experience storyboard — abstract wireframes of a customer-facing flow, each stage with something to do (no real catalogue, prices or payments)', ['work/customer-product']],
  ['sig-data-slab', 'foreground', 'Data slab — a window onto a synthetic, very large data set', ['work/internal-crm']],
  ['sig-surface-compare', 'foreground', 'Surface compare — drag to peel a screen back to its structure', ['company']],
  ['sig-principle-stack', 'foreground', 'Principle stack — cards that pile as you scroll (CSS sticky + scroll-driven settle)', ['company/principles']],
  ['sig-boundary-review', 'foreground', 'Boundary review — tick questions, rings and bars fill, copy what is left', ['company/security']],
  ['sig-chronology-scrubber', 'foreground', 'Chronology scrubber — drag or play through undated phases; the ink follows', ['company/timeline']],
  ['sig-areas-explorer', 'foreground', 'Areas explorer — strips open as you point, neighbours fold to a label', ['company/careers']],
  ['sig-system-index', 'foreground', 'System index — large rows, a red rule between them, a preview trailing the cursor', ['systems']],
  ['sig-needs-finder', 'foreground', 'Needs finder — pick what you are trying to do and the matching area lights', ['systems']],
  ['sig-ops-flow', 'foreground', 'Ops flow — send a request and a token glides through four stages', ['systems/operational-management']],
  ['sig-order-path', 'foreground', 'Order path — an order as a state machine you can run, with a settlement ledger', ['systems/commerce-infrastructure']],
  ['sig-rule-chain', 'foreground', 'Rule chain — pick a trigger, a guard and an action and run the chain step by step', ['systems/automation']],
  ['sig-console-composer', 'foreground', 'Console composer — assemble a console from abstract panels (shapes only)', ['systems/internal-platforms']],
  ['sig-view-shift', 'foreground', 'View shift — one set of records, four surfaces; markers glide between layouts', ['systems/data-interfaces']],
  ['sig-boundary-membrane', 'foreground', 'Boundary membrane — twelve records behind a membrane; choose a role and the records it may reach cross to the outside', ['systems/client-portals']],
  ['sig-research-bench', 'foreground', 'Research bench — three studies running on the page: scene budget, a still state for motion, focus you can follow', ['systems/research-systems']],
  ['sig-accordion-list', 'foreground', 'Accordion list — disclosures with a scrambling code and a turning plus', ['north']],
  ['sig-gate-walk', 'foreground', 'Gate walk — tick what a gate asks and the runner passes to the next stage', ['north/engineering']],
  ['sig-component-bench', 'foreground', 'Component bench — change the variant, size and state of the site\'s real Button, Pill and KeyCap and read the code it makes', ['north/interface-lab']],
  ['sig-easing-studio', 'foreground', 'Easing studio — drag Bézier handles, a ball travels the curve, the feel is described in words', ['north/motion-systems']],
  ['sig-toolchain-map', 'foreground', 'Toolchain map — switch a check off and see what could slip through', ['north/tooling']],
  ['sig-architecture-explorer', 'foreground', 'Architecture explorer — the layers of this website; trace a page view', ['engineering']],
  ['sig-scene-lab', 'foreground', 'Scene lab — view the site\'s own canvas scenes, density, still frame', ['lab']],
  ['sig-contact-studio', 'foreground', 'Contact studio — pick a subject, write (or drop in a starter), watch the envelope fill, open in your mail app or copy the address; nothing is sent from the page', ['contact']],
  ['sig-site-directory', 'foreground', 'Site directory — every page, grouped and filterable, with "take me somewhere"', ['sitemap']],
  ['sig-data-journey', 'foreground', 'Data journey — what leaves your browser for each thing you might do', ['legal/privacy']],
  ['sig-clause-finder', 'foreground', 'Clause finder — filter plain-language clauses by text or topic', ['legal/terms']],
  ['sig-storage-inspector', 'foreground', 'Storage inspector — live read of what this site keeps in your browser', ['legal/cookies']],
  ['sig-keyboard-map', 'foreground', 'Keyboard map — press a real key (or tap a cap) to see what it does here', ['legal/accessibility']],
  ['page-404', 'foreground', '404 — nearest real pages by edit distance, under proximity-reactive type', ['404']],

  // ---- signature blocks added with the library, trust, company, development and systems reference pages ----
  ['sig-article-art', 'foreground', 'ArticleArt — The hero object of a guide: its drawing, large. It draws itself in once, and again whenever you point at it.', ['/insights/animation-budgets', '/insights/api-contracts', '/insights/audit-trails', '/insights/handover', '/insights/idempotency', '/insights/permissions', '/insights/runbooks', '/insights/triggers']],
  ['sig-audit-log', 'foreground', 'AuditLog — An audit trail is judged by the questions it can answer. Choose which fields a log records; the questions people actually ask light up as answerable — or go dark, with the missing field named.', ['/insights/audit-trails']],
  ['sig-brand-board', 'foreground', 'BrandBoard — The brand as the site actually uses it, in five panels: the mark and the room it needs, the colours (click to copy; each one\'s contrast on the site\'s black is calculated, not claimed), the three typefaces,…', ['/company/brand']],
  ['sig-bug-catcher', 'foreground', 'BugCatcher — Which kind of check catches which kind of problem? Switch checks on and off and watch what slips through.', ['/north/quality']],
  ['sig-capability-matrix', 'foreground', 'CapabilityMatrix — What an operational system is usually made of, and which kind of system tends to need what.', ['/systems/capabilities']],
  ['sig-claims-ledger', 'foreground', 'ClaimsLedger — The trust centre\'s ledger: three columns — what the site does, what it does not claim, and what is still open — each row a disclosure that says how you can check it for yourself and links to the page that…', ['/trust']],
  ['sig-component-gallery', 'foreground', 'ComponentGallery — A family of interface components, each shown live. Pick one from the list (or arrive with its name in the address); see it working, narrowed to a phone if you like, then read how to use it, its props, the…', ['/north/components/content', '/north/components/data', '/north/components/feedback', '/north/components/inputs', '/north/components/navigation', '/north/components/overlays']],
  ['sig-contract-diff', 'foreground', 'ContractDiff — A response, three consumers, and a set of changes you can make to it. Each consumer reads the response in its own way, so each change breaks some and spares others — which is the whole lesson of a contract.', ['/insights/api-contracts']],
  ['sig-contrast-checker', 'foreground', 'ContrastChecker — Two colours in, the WCAG contrast ratio out, with a verdict for each kind of thing that has to be read, and the nearest passing colour when it falls short.', ['/resources/tools/contrast']],
  ['sig-cron-explainer', 'foreground', 'CronExplainer — Paste a schedule, read it in plain English, and see the next times it will run — in your own time zone or in UTC.', ['/resources/tools/cron']],
  ['sig-decision-record', 'foreground', 'DecisionRecord — A decision record builder. Fill in what was decided and why; the Markdown appears beside it, ready to commit next to the code.', ['/resources/tools/decision-record']],
  ['sig-document-reader', 'foreground', 'DocumentReader — A long-form document reader — for legal text, policies, handbooks and articles.', ['/insights/animation-budgets', '/insights/api-contracts', '/insights/audit-trails', '/insights/handover', '/insights/idempotency', '/insights/permissions', '/insights/runbooks', '/insights/triggers', '/legal/acceptable-use', '/legal/accessibility', '/legal/complaints', '/legal/cookies', '/legal/copyright', '/legal/disclaimer', '/legal/linking', '/legal/privacy', '/legal/retention', '/legal/terms', '/north/accessibility', '/north/handbook', '/trust/disclosure', '/work/how-to-read']],
  ['sig-download-shelf', 'foreground', 'DownloadShelf — Twelve documents you can keep. Each is generated in your browser when you press the button — nothing is fetched — so the ones built from the site\'s own data (the glossary, the page list) are always in step…', ['/resources/downloads']],
  ['sig-faq-desk', 'foreground', 'FaqDesk — Questions and answers with a desk of categories on the left and a search field above the list.', ['/company/faq']],
  ['sig-frame-budget', 'foreground', 'FrameBudget — The frame budget, measured rather than described. Choose how many boxes to animate and which property moves them; press Run and the page really animates them for a couple of seconds while counting the…', ['/insights/animation-budgets']],
  ['sig-glossary-browser', 'foreground', 'GlossaryBrowser — Every term the site uses, in plain language: search, filter by area, jump by letter, copy a link to one term.', ['/resources/glossary']],
  ['sig-handover-pack', 'foreground', 'HandoverPack — A handover pack, item by item. Tick what is in it and a ring fills; a new teammate\'s first-change time is estimated from what they would have to work out for themselves, and the one missing thing that hurts…', ['/insights/handover']],
  ['sig-hiring-path', 'foreground', 'HiringPath — What a conversation about working at North looks like, stage by stage, from either side of the table.', ['/company/hiring']],
  ['sig-idempotency-demo', 'foreground', 'IdempotencyDemo — A payment request whose answer gets lost on the way back. With no idempotency key the client retries and the customer is charged twice; with one, the server recognises the retry and replays its first answer.', ['/insights/idempotency']],
  ['sig-insight-library', 'foreground', 'InsightLibrary — The guides, as a library: filter by area, search, sort by length, and see at a glance which ones have something to play with.', ['/insights']],
  ['sig-integration-atlas', 'foreground', 'IntegrationAtlas — Six ways to connect two systems, and two of them at a time. Choose any two and every row compares them.', ['/systems/integrations']],
  ['sig-kit-index', 'foreground', 'KitIndex — The front door of the interface kit: every component, found by name or by what it is for.', ['/north/components']],
  ['sig-legal-centre', 'foreground', 'LegalCentre — Every legal document in one place. The title, section count and reading time of each card are read from the document itself, and the bar along the bottom is its shape: one segment per section, as wide as…', ['/legal']],
  ['sig-licence-table', 'foreground', 'LicenceTable — Every library and typeface the site is built with, its version and its licence, as published by the packages themselves.', ['/trust/licences']],
  ['sig-lifecycle-line', 'foreground', 'LifecycleLine — A system\'s life as five stages, with an illustrative shape of the effort each asks for.', ['/systems/lifecycle']],
  ['sig-live-status', 'foreground', 'LiveStatus — Not a status page for the company — a status page for YOUR visit. Everything on it is measured by your own browser, live: the frame rate of this very page, how the page loaded, what the connection looks…', ['/trust/status']],
  ['sig-page-outline', 'foreground', 'PageOutline — A screen reader\'s-eye view of the page you are reading: its title and language, its headings as an outline, its landmarks, how many places the Tab key stops, and a few things that go wrong.', ['/north/accessibility']],
  ['sig-permission-matrix', 'foreground', 'PermissionMatrix — Roles against actions. Toggle what a role may do, switch between "roles only" and "roles plus scope" (own records, own team), then act as a person and see the decision — and the rule that made it.', ['/insights/permissions']],
  ['sig-press-kit', 'foreground', 'PressKit — Everything someone writing about the company needs to get it right: the company in three lengths (each one copies in a press), a fact sheet where every line copies, and the mark in the files the site itself…', ['/company/press']],
  ['sig-project-rhythm', 'foreground', 'ProjectRhythm — How a piece of work moves, as a stepper you can walk (or let walk itself).', ['/company/how-we-work']],
  ['sig-readiness-check', 'foreground', 'ReadinessCheck — Twenty questions to ask before something goes live, in five groups. Answer Yes, Partly, No or Not applicable; the gaps come back as a list to act on, which can be copied or downloaded.', ['/resources/tools/readiness']],
  ['sig-release-notes', 'foreground', 'ReleaseNotes — The site\'s history, told in chapters, newest first. The site is not versioned and nothing on it is derived from repository dates, so the chapters carry no dates: they are in the order things happened.', ['/resources/changelog']],
  ['sig-resource-desk', 'foreground', 'ResourceDesk — The four shelves of the resource centre, each with a live count read from the data behind it and a small peek at what is on it.', ['/resources']],
  ['sig-runbook-walk', 'foreground', 'RunbookWalk — The same incident, two runbooks. One explains the system; the other starts from the symptom.', ['/insights/runbooks']],
  ['sig-service-map', 'foreground', 'ServiceMap — Every service your browser may be asked to contact for this site, one at a time: what it receives, when, whether you can avoid it, and what you would see if you did.', ['/trust/third-parties']],
  ['sig-stack-map', 'foreground', 'StackMap — The site\'s stack as slabs, top to bottom: what the visitor touches down to what builds it.', ['/north/stack']],
  ['sig-token-inspector', 'foreground', 'TokenInspector — The design tokens, read from the stylesheet this page is wearing. Search them, group them, see what each one is, copy it as var(--name).', ['/north/design-tokens']],
  ['sig-tool-bench', 'foreground', 'ToolBench — The five browser tools, each with what it does and what it never does.', ['/resources/tools']],
  ['sig-trigger-compare', 'foreground', 'TriggerCompare — Three triggers, one burst of work. Slide the size of the burst, the number of workers and the cron interval, and compare how long the average job waits and how big the backlog gets.', ['/insights/triggers']],
  ['sig-type-scale-tool', 'foreground', 'TypeScaleTool — A type scale: one base size multiplied again and again by one ratio, so the sizes belong together.', ['/resources/tools/type-scale']],

  // ---- page endings (closers): one composition for each page, never a call to action ----
  ['end-receipt', 'foreground', 'Receipt — An itemised receipt of what the site holds for this visitor, read live from the browser and "printed" line by line.', ['/legal/privacy']],
  ['end-terms-card', 'foreground', 'TermsCard — The terms on a single card that turns over: what you can do on one side, what not to lean on on the other.', ['/legal/terms']],
  ['end-purge', 'foreground', 'Purge — A purge button for the site\'s own items in your browser. One press runs a short "wipe", removes only the keys that belong to this site, and shows what is left (which should be nothing of ours).', ['/legal/cookies']],
  ['end-prefs-panel', 'foreground', 'PrefsPanel — Display preferences for this view — text size, line spacing, contrast, a calm mode and the single-key shortcuts — that take effect at once and last only until the page is reloaded.', ['/legal/accessibility']],
  ['end-fair-line', 'foreground', 'FairLine — Eight things a visitor might do. Call each one fine or not fine; the answer is revealed with the policy\'s reasoning, and a running tally shows how your reading compares.', ['/legal/acceptable-use']],
  ['end-mark-desk', 'foreground', 'MarkDesk — A desk that answers "may I…?". Pick a use from the list (arrow keys move between them); a verdict is stamped onto the slip with the one line that explains it and, where there is one, the page to read next.', ['/legal/copyright']],
  ['end-fine-print', 'foreground', 'FinePrint — The disclaimers in genuinely tiny type, with a lens that follows the pointer and reads the line under it at a size you can read.', ['/legal/disclaimer']],
  ['end-lifetime-ruler', 'foreground', 'LifetimeRuler — A ruler of moments. Slide the marker (or use the arrow keys) and each item shows whether it is still alive at that moment — so "how long is it kept?" is answered by watching things go out.', ['/legal/retention']],
  ['end-parcel-track', 'foreground', 'ParcelTrack — A tracking line for a report: four stations, a parcel that travels to the one you choose, and who handles that stage.', ['/legal/complaints']],
  ['end-link-builder', 'foreground', 'LinkBuilder — Pick a page (and, for the long documents, a section) and a format; the link comes out written the way the linking policy asks: the page\'s own title as the text, the canonical address as the target.', ['/legal/linking']],
  ['end-status-ledger', 'foreground', 'StatusLedger — An honest ledger of where each document stands. The ticks arrive one by one as the ledger scrolls in; the column nobody has ticked yet says so.', ['/legal']],
  ['end-self-audit', 'foreground', 'SelfAudit — Four checks you run yourself, on this page, in your browser. Each says what it will look at, then what it found — so "trust us" becomes "look".', ['/trust']],
  ['end-frame-tape', 'foreground', 'FrameTape — A strip-chart recorder for this page. Every frame the browser draws is one column on the tape — tall and red when it took long — and three counters tick from the same measurements.', ['/trust/status']],
  ['end-scope-target', 'foreground', 'ScopeTarget — A target for a vulnerability-reporting scope: the bullseye is what is in scope, the rings outside it are what is not.', ['/trust/disclosure']],
  ['end-host-scan', 'foreground', 'HostScan — "Where has this tab been?" — read from the browser\'s own list of requests, grouped by host, each one matched against the hosts this site says it uses.', ['/trust/third-parties']],
  ['end-notice-file', 'foreground', 'NoticeFile — The notices page\'s ending: the whole list as a plain NOTICE file you can read here, copy, or download.', ['/trust/licences']],
  ['end-end-credits', 'foreground', 'EndCredits — Roll credits for the company: not people, but the disciplines, the work and the parts it is made from.', ['/company']],
  ['end-review-draw', 'foreground', 'ReviewDraw — A deck of the principles. Draw one and it turns up with a single question to put to your next design review — the principle as something to ask, not something to admire.', ['/company/principles']],
  ['end-gate-run', 'foreground', 'GateRun — A request walks the gates one at a time and stops at the first that says no.', ['/company/security']],
  ['end-horizon', 'foreground', 'Horizon — The company\'s phases as strata under a horizon: the oldest lies deepest, the newest sits just beneath the surface, and above the line is the part that has not been told yet.', ['/company/timeline']],
  ['end-fit-radar', 'foreground', 'FitRadar — Set how much each area of the work draws you, and a radar fills in. The area you lean towards most is named.', ['/company/careers']],
  ['end-prep-sheet', 'foreground', 'PrepSheet — The "before a first conversation" sheet: what is worth having to hand.', ['/company/how-we-work']],
  ['end-ask-deck', 'foreground', 'AskDeck — Questions a candidate is welcome to ask, on cards. Turn one to see why it is a good question to ask — and what a good answer would sound like.', ['/company/hiring']],
  ['end-ask-the-site', 'foreground', 'AskTheSite — Ask the whole site a question. It searches every page\'s title and text with the same engine as ⌘K and lays the best answers out here, with the sentence that matched.', ['/company/faq']],
  ['end-name-style', 'foreground', 'NameStyle — How to write the name: four quick choices, each answered the moment you make it, and a one-line style summary at the end.', ['/company/press']],
  ['end-mark-misuse', 'foreground', 'MarkMisuse — The mark, used wrongly six ways and rightly once — each tile carrying the one-line reason.', ['/company/brand']],
  ['end-takeaway-deck', 'foreground', 'TakeawayDeck — The few things worth keeping, as a deck you page through. The top card lifts away to the back; arrow keys work on the deck.', ['/insights/idempotency']],
  ['end-log-line', 'foreground', 'LogLine — Write one audit entry. Fill in who, what, to what and why; the server\'s part (time, request, source) is added for you, and the entry comes out as a structured line you can copy.', ['/insights/audit-trails']],
  ['end-least-privilege', 'foreground', 'LeastPrivilege — Slide how much an account may do and watch the blast radius — what a stolen password or a slip of the mouse could reach — grow with it.', ['/insights/permissions']],
  ['end-pager-card', 'foreground', 'PagerCard — A one-page runbook template, laid out as a card. Read it here, copy it, or download it as Markdown and fill it in for a real service.', ['/insights/runbooks']],
  ['end-which-one', 'foreground', 'WhichOne — Three questions, one recommendation. Answer them about the job in front of you and the helper names the trigger that fits — and why the other two don\'t.', ['/insights/triggers']],
  ['end-deprecation-notice', 'foreground', 'DeprecationNotice — Write the notice before you break anything. Say what is going, what replaces it and how long people have; out come the announcement and the two response headers (Deprecation and Sunset) that let tools…', ['/insights/api-contracts']],
  ['end-readme-maker', 'foreground', 'ReadmeMaker — A README that the next person can use. Choose the sections; the skeleton is assembled beside you, with a prompt under every heading saying what belongs there.', ['/insights/handover']],
  ['end-ease-pick', 'foreground', 'EasePick — The same menu opening, four times, each on a different easing. Pick the one that feels right, then see what the rule of thumb says — and why.', ['/insights/animation-budgets']],
  ['end-random-read', 'foreground', 'RandomRead — Can\'t choose? A reel of the guide titles spins and lands on one.', ['/insights']],
  ['end-reading-list', 'foreground', 'ReadingList — Build a reading list from the pages of this site: tick what to read, or start from a preset; the list comes out as Markdown with the links and an honest estimate of the time, ready to send to someone.', ['/resources']],
  ['end-flash-deck', 'foreground', 'FlashDeck — Flashcards from the glossary. Read the term, say what it means, turn the card, and mark whether you had it.', ['/resources/glossary']],
  ['end-history-bar', 'foreground', 'HistoryBar — The whole history of the site as one chart: a row for each chapter, a bar as long as the number of notes in it, cut into what was added, changed and fixed.', ['/resources/changelog']],
  ['end-bundle-builder', 'foreground', 'BundleBuilder — Choose several of the downloadable documents and have them joined into one Markdown file with a contents list — built here, in the page, when you press the button.', ['/resources/downloads']],
  ['end-cheat-sheet', 'foreground', 'CheatSheet — One printable page that holds what the five tools turn on: the thresholds, the ratios, the field ranges, the groups, the headings.', ['/resources/tools']],
  ['end-pair-matrix', 'foreground', 'PairMatrix — Check a whole palette at once. Paste colours, and every text-on-background pairing is graded in a grid, so the ones that never work are visible before anyone designs with them.', ['/resources/tools/contrast']],
  ['end-clamp-maker', 'foreground', 'ClampMaker — Fluid type without media queries: a font size that grows smoothly between two viewport widths and stops at both ends.', ['/resources/tools/type-scale']],
  ['end-dst-trap', 'foreground', 'DstTrap — Daylight-saving time, as it bites a schedule. Choose a zone and a time of day; the page finds the day or days this year when the clocks change in that zone and says what happens to your time on each:…', ['/resources/tools/cron']],
  ['end-launch-timeline', 'foreground', 'LaunchTimeline — The two weeks around a launch, as a track you walk along: what to do at each stop, with the items you can tick and a ring that fills.', ['/resources/tools/readiness']],
  ['end-pre-mortem', 'foreground', 'PreMortem — The pre-mortem: imagine a year has passed and the decision turned out badly.', ['/resources/tools/decision-record']],
  ['end-symptom-router', 'foreground', 'SymptomRouter — Start from what is going wrong, not from what the team is called. Choose the symptom closest to yours and the page names the discipline that deals with it, why, and where else to look.', ['/north']],
  ['end-spot-the-bug', 'foreground', 'SpotTheBug — A review exercise. Read a short piece of code the way a reviewer would, mark the lines you would stop, and press Check.', ['/north/engineering']],
  ['end-layer-sort', 'foreground', 'LayerSort — Where does it belong? Eight small responsibilities, four layers.', ['/north/architecture']],
  ['end-state-sheet', 'foreground', 'StateSheet — The seven states every control owns, shown side by side for three controls, and a live row of the real thing underneath.', ['/north/interface-lab']],
  ['end-motion-modes', 'foreground', 'MotionModes — One menu opening under three motion policies. The site follows the device\'s reduced-motion setting, and also offers a calm display setting of its own.', ['/north/motion-systems']],
  ['end-pipeline-maker', 'foreground', 'PipelineMaker — Assemble a checks pipeline: choose the checks, put them in order, and a workflow file comes out, with the same sequence as a local script.', ['/north/tooling']],
  ['end-page-vitals', 'foreground', 'PageVitals — The page you are on, weighed: its elements, its requests, its size, its first paint and the frame rate it is managing right now.', ['/engineering']],
  ['end-sigil-maker', 'foreground', 'SigilMaker — A figure drawn from a word. The same word always draws the same shape, so it is a signature rather than a random picture.', ['/lab']],
  ['end-done-builder', 'foreground', 'DoneBuilder — Write a definition of done. Choose what must be true before work counts as finished; the list becomes a card you can print or paste.', ['/north/handbook']],
  ['end-token-playground', 'foreground', 'TokenPlayground — Change four tokens and watch a small interface follow. The values are set on the preview alone, as custom properties — which is exactly how a real design system restyles everything at once.', ['/north/design-tokens']],
  ['end-what-if-remove', 'foreground', 'WhatIfRemove — Pull one part out of the stack and see what goes with it. A way of asking how much each dependency really carries.', ['/north/stack']],
  ['end-chaos-wheel', 'foreground', 'ChaosWheel — Break it on purpose. Spin for a way things go wrong, read what should happen and how to rehearse it, and mark the ones you have tried.', ['/north/quality']],
  ['end-alt-text-lab', 'foreground', 'AltTextLab — Write the alt text for four pictures, each a different problem: a chart, an ornament, an icon in a button, an illustration.', ['/north/accessibility']],
  ['end-try-site', 'foreground', 'TrySite — Five things worth trying on this site, each a real control: they open the actual search, the actual shortcuts panel, the actual blueprint mode, the actual calm setting, and a page chosen at random.', ['/']],
  ['end-operation-brief', 'foreground', 'OperationBrief — Write the brief the first conversation needs, before the conversation.', ['/systems']],
  ['end-bottleneck', 'foreground', 'Bottleneck — An operation moves at the pace of its slowest step. Five steps, each with people and minutes per item: the slowest is marked, and adding a person anywhere else changes nothing.', ['/systems/operational-management']],
  ['end-last-item', 'foreground', 'LastItem — The classic race: two people press Buy on the last item at once. Step through three ways of handling it and see which ones sell the item twice.', ['/systems/commerce-infrastructure']],
  ['end-automation-math', 'foreground', 'AutomationMath — Is it worth automating? Put in how long a job takes, how often it happens, what it costs to build and what it costs to keep running; the page says when it pays for itself, if it ever does.', ['/systems/automation']],
  ['end-lineage', 'foreground', 'Lineage — “Where did this number come from?” Press the figure and follow it down, hop by hop, to the system that produced it, seeing what must be recorded at each hop for the trail to be walkable.', ['/systems/internal-platforms']],
  ['end-role-lens', 'foreground', 'RoleLens — One record, four people. Each role needs a few of the fields and not the rest.', ['/systems/data-interfaces']],
  ['end-exposure-desk', 'foreground', 'ExposureDesk — Design what a customer portal shows. Each field of an order says what the usual rule is; switch fields on and off and the preview changes, with a warning for anything that should never leave the building.', ['/systems/client-portals']],
  ['end-hypothesis-card', 'foreground', 'HypothesisCard — A small card for a small experiment. A good hypothesis can be wrong, says what would show it, and says when to stop.', ['/systems/research-systems']],
  ['end-size-up', 'foreground', 'SizeUp — How big is it, really? Five questions about a system, each a judgement, and the page says what shape of work that adds up to: a focused tool, a platform or a programme, with what changes at each size.', ['/systems/capabilities']],
  ['end-integration-sheet', 'foreground', 'IntegrationSheet — The agreement that decides whether an integration survives its first bad day.', ['/systems/integrations']],
  ['end-sunset-plan', 'foreground', 'SunsetPlan — Plan the end while you are building the start. Choose what applies to the system you are retiring and how much notice people get; out comes an ordered plan counted back from the day it is switched off.', ['/systems/lifecycle']],
  ['end-case-exam', 'foreground', 'CaseExam — Six questions to put to any case study, put to this site\'s own. For each of the four, the page says plainly what is answered, what is only partly answered and what is not said at all.', ['/work/how-to-read']],
  ['end-work-compare', 'foreground', 'WorkCompare — Put any two of the four side by side. The rows are the things the work pages say; where a row is the same for both it is marked, because what two pieces of work share is as telling as how they differ.', ['/work']],
  ['end-channel-count', 'foreground', 'ChannelCount — Why coordination gets harder faster than the team grows. Everyone telling everyone needs a channel for every pair of people: the count grows with the square of the headcount.', ['/work/musebase']],
  ['end-fixed-step', 'foreground', 'FixedStep — Why a game engine does not simply use the time since the last frame. The same ball is dropped three ways: with a tiny step (the answer), with a fixed step that catches up however slowly frames arrive, and…', ['/work/yk-engine']],
  ['end-funnel-math', 'foreground', 'FunnelMath — Every step between a first look and a confirmed purchase takes some people away.', ['/work/customer-product']],
  ['end-lookup-race', 'foreground', 'LookupRace — Finding one row among millions. Three ways, with the number of steps each takes as the table grows, and then the real thing: the page builds half a million rows in your browser and times each method for you.', ['/work/internal-crm']],
  ['end-kit-picker', 'foreground', 'KitPicker — “Which component?” — answer what you are trying to do, then narrow it, and the page names the one or two components that fit, with the reason, and links to each in its gallery.', ['/north/components']],
  ['end-form-builder', 'foreground', 'FormBuilder — Choose the fields a form needs and the page builds it from the kit\'s own components, checks it when you send it (focus goes to the first problem, and a summary is announced), and writes the JSX out so you…', ['/north/components/inputs']],
  ['end-wizard-run', 'foreground', 'WizardRun — A four-step flow, walked. The Stepper shows where you are; Next is held back until the step is complete and says why; when the step changes, focus moves to its heading so a keyboard or screen-reader user…', ['/north/components/navigation']],
  ['end-toast-bench', 'foreground', 'ToastBench — Fire the feedback components and watch what each one would announce.', ['/north/components/feedback']],
  ['end-data-shape', 'foreground', 'DataShape — “Show this data.” Pick the shape your data has and the page shows the component that suits it, drawn with sample data, with the reason — and the common wrong choice and why it fails.', ['/north/components/data']],
  ['end-focus-trap', 'foreground', 'FocusTrap — “Try to escape the dialog.” Open it and press Tab, Shift+Tab and Escape: a log beside it writes down where focus goes — in, round and round inside, and back to the button that opened it.', ['/north/components/overlays']],
  ['end-reading-column', 'foreground', 'ReadingColumn — Set a reading column. Slide the measure (characters per line), the line height and the size, and change the face; the text reflows under your hands and the page says whether each setting is short,…', ['/north/components/content']],
  ['end-block-picker', 'foreground', 'BlockPicker — “Which block?” Say what you are trying to show and the page names the block that suits it, with the data that makes it, why it fits, and what people usually reach for instead.', ['/north/blocks']],

  // ---- data-first page blocks (components/page/blocks, made from the interface kit; the list is data/blockTypes.js) ----
  ['blk-callout', 'foreground', 'Callout block — one remark set apart from the text, worded by kind (note, tip, warning); it materialises out of a soft blur', ['/north/blocks']],
  ['blk-table', 'foreground', 'Table block — records in rows and columns; headers sort, and a wide table scrolls inside a named, focusable region', ['/north/blocks']],
  ['blk-timeline', 'foreground', 'Timeline block — things in the order they happen, down a line, told in words rather than dates', ['/north/blocks']],
  ['blk-faq', 'foreground', 'Faq block — questions and answers as disclosures; a closed answer is out of the tab order', ['/north/blocks', '/resources/downloads', '/contact']],
  ['blk-compare', 'foreground', 'Compare block — two or three ways of looking at a choice, side by side, each named in words', ['/north/blocks']],
  ['blk-snippet', 'foreground', 'Snippet block — code or data with a file name, light colouring and a copy button', ['/north/blocks']],
  ['blk-tabs', 'foreground', 'Tabs block — several short views of one subject, with ← → Home End moving between them', ['/north/blocks']],
  ['blk-quote', 'foreground', 'Quote block — a pull quote with its source; it arrives from a larger scale', ['/north/blocks']],
  ['blk-checklist', 'foreground', 'Checklist block — real checkboxes with a polite count; the ticks live in the page and are never stored', ['/north/blocks', '/trust/disclosure', '/north/accessibility']],
  ['blk-facts', 'foreground', 'Facts block — labels and their values in a real description list', ['/north/blocks']],
  ['blk-links', 'foreground', 'Links block — cards that each hold one link to a page of the site', ['/north/blocks']],
  ['blk-numbers', 'foreground', 'Numbers block — large labelled figures, how they moved in words, and a sparkline when there is a series', ['/north/blocks']],

  // ---- global: announcing a page change ----
  ['global-route-announcer', 'foreground', 'Route announcer — says the new page’s title in a polite status region after a page change, and hands focus to the main region when the link used has gone', ['every page']],
];

export const animationInventory = [
  ...BACKGROUND_SCENES.map(([id, name]) => ({ id: `bg-${id}`, type: 'background', name, usedOn: [] })),
  ...OTHER.map(([id, type, name, usedOn]) => ({ id, type, name, usedOn })),
  ...FOREGROUND.map(([id, type, name, usedOn]) => ({ id, type, name, usedOn })),
];

export const INVENTORY_COUNT = animationInventory.length;

export const inventoryByType = animationInventory.reduce((acc, e) => {
  (acc[e.type] = acc[e.type] || []).push(e);
  return acc;
}, {});
