import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { chromium } from 'playwright-core';

const chrome = [process.env.CHROME_PATH, 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe', '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'].find((file) => file && existsSync(file));
if (!chrome) throw new Error('Set CHROME_PATH to an installed Chromium browser.');
const base = process.env.QA_BASE || 'http://127.0.0.1:5174';
const browser = await chromium.launch({ executablePath: chrome, headless: true });
const desktop = await browser.newContext({ viewport: { width: 1440, height: 900 } });
await desktop.addInitScript(() => { sessionStorage.setItem('hnx.boot.complete', '1'); });
const page = await desktop.newPage();

await page.goto(base + '/projects', { waitUntil: 'domcontentloaded' });
await page.getByRole('heading', { name: 'Explore the work.' }).waitFor();
const search = page.getByRole('searchbox', { name: 'Search projects' });
await search.fill('Rune');
assert.match(await page.getByRole('status').first().textContent(), /1 public repository/);
await search.fill('');
await page.getByRole('button', { name: 'Engine', exact: true }).click();
assert.match(await page.getByRole('status').first().textContent(), /2 public repositories/);
await page.getByRole('button', { name: 'All', exact: true }).first().click();
await page.getByRole('button', { name: 'Index' }).click();
assert.equal(await page.locator('ul[class*="indexList"] li').count(), 8);
await page.reload({ waitUntil: 'domcontentloaded' });
await page.getByRole('heading', { name: 'Explore the work.' }).waitFor();
assert.equal(await page.getByRole('button', { name: 'Index' }).getAttribute('aria-pressed'), 'true');
await page.getByRole('button', { name: /Rust/ }).click();
assert.match(await page.locator('[aria-live="polite"]').last().textContent(), /Rune/);
await page.getByRole('group', { name: 'Choose a repository for the graph' }).getByRole('button', { name: 'Rune' }).click();
assert.match(await page.getByRole('status').last().textContent(), /Rune.*1 connected repository/);
assert.equal(await page.getByRole('list', { name: 'Connected repositories' }).getByRole('link', { name: /mocha-browser/ }).count(), 1);
await page.getByRole('list', { name: 'Connected repositories' }).getByRole('link', { name: /mocha-browser/ }).click();
await page.waitForURL('**/projects/mocha-browser');
assert.equal(await page.getByRole('link', { name: 'View source', exact: true }).getAttribute('href'), 'https://github.com/Adventnl/mocha-browser');
await page.goto(base + '/projects/yk-engine', { waitUntil: 'domcontentloaded' });
const tree = page.getByRole('region', { name: 'Inside the root.' });
await tree.locator('ul li').first().waitFor();
assert.equal(await tree.locator('ul').first().locator('li').count(), 8);
await tree.getByRole('button', { name: /Show .* more selected entries/ }).click();
assert.equal(await tree.locator('ul').first().locator('li').count(), 17);

await page.keyboard.press('Control+k');
const dialog = page.getByRole('dialog', { name: 'Search Hanoryx Systems' });
assert.equal(await dialog.isVisible(), true);
assert.match(await dialog.getByRole('option').first().textContent(), /Home/);
const searchInput = dialog.getByRole('combobox', { name: 'Search pages and public projects' });
assert.equal(await searchInput.getAttribute('aria-controls'), await dialog.getByRole('listbox').getAttribute('id'));
assert.equal(await searchInput.getAttribute('aria-activedescendant'), await dialog.getByRole('option', { selected: true }).getAttribute('id'));
await searchInput.fill('profiling');
assert.match(await dialog.getByRole('option').first().textContent(), /YK-Engine/);
await searchInput.fill('visual lab');
await page.keyboard.press('Enter');
await page.waitForURL('**/lab');
assert.equal(await dialog.isVisible(), false);
await page.getByRole('button', { name: /Network constellation/ }).click();
assert.match(await page.locator('[class*="viewerLabel"]').textContent(), /Network constellation/i);
await page.goto(base + '/engineering', { waitUntil: 'domcontentloaded' });
await page.getByRole('group', { name: 'Site architecture layers' }).getByRole('button', { name: /Runtime/ }).click();
assert.match(await page.locator('[aria-live="polite"]').last().textContent(), /Frame scheduler/);
await page.goto(base + '/timeline', { waitUntil: 'domcontentloaded' });
await page.getByRole('link', { name: 'View repository' }).first().click();
await page.waitForURL('**/projects/yk-engine');
await page.keyboard.press('Control+k');
await dialog.getByRole('button', { name: 'Close search' }).click();
assert.equal(await dialog.isVisible(), false);
await page.keyboard.press('Control+k');
await dialog.getByRole('combobox').fill('console architecture');
await page.keyboard.press('Enter');
await page.waitForURL('**/work/north-console');
assert.equal(await page.getByRole('heading', { level: 1 }).count(), 1);
await desktop.close();

const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
await mobile.addInitScript(() => { sessionStorage.setItem('hnx.boot.complete', '1'); });
const mobilePage = await mobile.newPage();
await mobilePage.goto(base + '/', { waitUntil: 'domcontentloaded' });
await mobilePage.getByRole('button', { name: 'Open menu' }).click();
assert.equal(await mobilePage.getByRole('navigation', { name: 'Mobile' }).isVisible(), true);
assert.equal(await mobilePage.getByRole('button', { name: 'Close mobile navigation' }).isVisible(), true);
await mobilePage.getByRole('button', { name: 'Toggle Work routes' }).click();
assert.equal(await mobilePage.getByRole('link', { name: /Public repositories/ }).isVisible(), true);
await mobilePage.keyboard.press('Escape');
await mobilePage.getByRole('navigation', { name: 'Mobile' }).waitFor({ state: 'detached' });
await mobilePage.setViewportSize({ width: 320, height: 844 });
await mobilePage.getByRole('button', { name: 'Search site' }).click();
const mobileDialog = mobilePage.getByRole('dialog', { name: 'Search Hanoryx Systems' });
const mobileDialogBox = await mobileDialog.boundingBox();
assert.ok(mobileDialogBox.x >= 0 && mobileDialogBox.x + mobileDialogBox.width <= 320, 'Search must fit a 320px viewport');
await mobileDialog.getByRole('button', { name: 'Close search' }).click();
assert.equal(await mobileDialog.isVisible(), false);
await mobile.close();

const fresh = await browser.newContext({ viewport: { width: 1280, height: 800 } });
const firstVisit = await fresh.newPage();
await firstVisit.goto(base + '/', { waitUntil: 'domcontentloaded' });
await firstVisit.getByRole('button', { name: 'START' }).click();
assert.equal(await firstVisit.locator('audio').evaluate((audio) => audio.paused), true, 'Boot must not start audio');
await firstVisit.getByRole('button', { name: 'Skip intro' }).click();
await fresh.close();
await browser.close();
console.log('Project, graph, architecture, timeline, lab, command, and mobile navigation interactions passed');
